<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Formal Warehouse Status Report</title>
    <style>
        @page {
            margin: 100px 50px;
        }
        header {
            position: fixed;
            top: -60px;
            left: 0px;
            right: 0px;
            height: 50px;
            border-bottom: 2px solid #333;
            text-align: center;
            line-height: 35px;
        }
        footer {
            position: fixed; 
            bottom: -60px; 
            left: 0px; 
            right: 0px;
            height: 50px; 
            text-align: center;
            font-size: 10px;
            color: #777;
            border-top: 1px solid #ddd;
            padding-top: 10px;
        }
        .pagenum:before {
            content: counter(page);
        }
        body {
            font-family: 'Times New Roman', Times, serif; /* More formal font */
            font-size: 12pt;
            color: #000;
            line-height: 1.4;
        }
        .letterhead {
            text-align: center;
            margin-bottom: 30px;
        }
        .letterhead h1 {
            margin: 0;
            font-size: 20pt;
            text-transform: uppercase;
            font-weight: bold;
        }
        .letterhead p {
            margin: 2px 0;
            font-size: 10pt;
            color: #444;
        }
        .report-title {
            text-align: center;
            text-decoration: underline;
            font-size: 16pt;
            font-weight: bold;
            margin-bottom: 5px;
        }
        .report-meta {
            text-align: center;
            font-size: 11pt;
            margin-bottom: 30px;
        }
        .section-title {
            background-color: #f2f2f2;
            padding: 5px 10px;
            font-size: 13pt;
            font-weight: bold;
            border-left: 5px solid #333;
            margin-top: 25px;
            margin-bottom: 15px;
            text-transform: uppercase;
        }
        .summary-box {
            display: table;
            width: 100%;
            margin-bottom: 20px;
        }
        .summary-item {
            display: table-cell;
            width: 33%;
            padding: 10px;
            border: 1px solid #ccc;
        }
        .summary-label {
            font-size: 9pt;
            font-weight: bold;
            color: #555;
            display: block;
        }
        .summary-value {
            font-size: 14pt;
            font-weight: bold;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        th {
            border: 1px solid #000;
            background-color: #e6e6e6;
            padding: 8px;
            text-align: left;
            font-size: 10pt;
            font-weight: bold;
        }
        td {
            border: 1px solid #000;
            padding: 6px 8px;
            font-size: 10pt;
        }
        .badge {
            font-weight: bold;
        }
        .signature-section {
            margin-top: 50px;
            width: 100%;
        }
        .signature-box {
            display: inline-block;
            width: 45%;
            text-align: center;
        }
        .signature-line {
            margin-top: 60px;
            border-top: 1px solid #000;
            width: 200px;
            margin-left: auto;
            margin-right: auto;
        }
        .confidential {
            color: red;
            font-weight: bold;
            font-size: 9pt;
            text-align: right;
        }
    </style>
</head>
<body>
    <header>
        EXTERNAL LOGISTICS V3.0 - OFFICIAL SYSTEM REPORT
    </header>

    <footer>
        Page <span class="pagenum"></span> | Generated by Warehouse System | Date: {{ date('Y-m-d H:i:s') }}
    </footer>

    <div class="letterhead">
        <div class="confidential">CONFIDENTIAL</div>
        <h1>PT. INVENTORY PERGUDANGAN INDONESIA</h1>
        <p>Jl. Industri Kawasan Strategis No. 12, Jakarta, Indonesia</p>
        <p>Tel: (021) 1234-5678 | Email: admin@warehouse-logistics.id</p>
    </div>

    <div class="report-title">WAREHOUSE STATUS AUDIT REPORT</div>
    <div class="report-meta">
        Ref No: WR/{{ date('Ymd') }}/{{ str_pad(rand(1, 999), 3, '0', STR_PAD_LEFT) }} <br>
        Period: {{ Carbon\Carbon::now()->format('F Y') }}
    </div>

    <div class="section-title">I. Executive Summary</div>
    <div class="summary-box">
        <div class="summary-item">
            <span class="summary-label">Total Inventory Units</span>
            <span class="summary-value">{{ number_format($stats['total_inventory']) }}</span>
        </div>
        <div class="summary-item" style="border-left: 0; border-right: 0;">
            <span class="summary-label">Storage Capacity Used</span>
            <span class="summary-value">{{ $stats['efficiency'] }}%</span>
        </div>
        <div class="summary-item">
            <span class="summary-label">Estimated Asset Value</span>
            <span class="summary-value">Rp {{ number_format($stats['total_value'], 0, ',', '.') }}</span>
        </div>
    </div>
    <p style="font-size: 10pt;">
        This document provides a comprehensive audit of the current warehouse status, including physical stock levels, storage efficiency, and recent movement historical data. As of the time of generation, the warehouse is operating at {{ $stats['efficiency'] }}% capacity.
    </p>

    <div class="section-title">II. Inventory Stock Manifest</div>
    <table>
        <thead>
            <tr>
                <th style="width: 15%;">SKU Code</th>
                <th style="width: 45%;">Product Description</th>
                <th style="width: 20%;">Category</th>
                <th style="width: 10%; text-align: center;">Qty</th>
                <th style="width: 10%; text-align: center;">Unit</th>
            </tr>
        </thead>
        <tbody>
            @foreach($products as $product)
            <tr>
                <td>{{ $product->sku }}</td>
                <td>{{ $product->name }}</td>
                <td>{{ $product->category->name ?? 'N/A' }}</td>
                <td style="text-align: center;">{{ number_format($product->total_qty ?? 0) }}</td>
                <td style="text-align: center;">{{ $product->unit->name ?? 'Pcs' }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div style="page-break-after: always;"></div>

    <div class="section-title">III. Recent Strategic Movements</div>
    <table>
        <thead>
            <tr>
                <th style="width: 20%;">Timestamp</th>
                <th style="width: 10%;">Type</th>
                <th style="width: 40%;">Product Description</th>
                <th style="width: 10%; text-align: center;">Qty</th>
                <th style="width: 20%;">Ref. Number</th>
            </tr>
        </thead>
        <tbody>
            @foreach($movements as $m)
            <tr>
                <td>{{ $m->movement_date->format('d/m/Y H:i') }}</td>
                <td style="text-align: center;" class="badge">
                    {{ strtoupper($m->movement_type) }}
                </td>
                <td>{{ $m->product->name }}</td>
                <td style="text-align: center;">{{ number_format($m->quantity) }}</td>
                <td>{{ $m->reference_type }} #{{ $m->reference_id }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="section-title">IV. Storage Node Utilization (Rack Detail)</div>
    <table>
        <thead>
            <tr>
                <th>Node ID</th>
                <th>Zone / Sector</th>
                <th style="text-align: center;">Used</th>
                <th style="text-align: center;">Capacity</th>
                <th style="text-align: center;">Utilization (%)</th>
            </tr>
        </thead>
        <tbody>
            @foreach($racks as $rack)
            <tr>
                <td>{{ $rack->code }}</td>
                <td>{{ $rack->zone->name ?? 'Unclassified' }}</td>
                <td style="text-align: center;">{{ number_format($rack->total_qty ?? 0) }}</td>
                <td style="text-align: center;">{{ number_format($rack->capacity) }}</td>
                <td style="text-align: center;">{{ round(($rack->total_qty / max(1, $rack->capacity)) * 100, 1) }}%</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="signature-section">
        <div class="signature-box">
            <p>Prepared By,</p>
            <div class="signature-line"></div>
            <p><strong>Warehouse Supervisor</strong></p>
            <p style="font-size: 8pt; margin: 0;">Date: {{ date('d M Y') }}</p>
        </div>
        <div class="signature-box" style="float: right;">
            <p>Approved By,</p>
            <div class="signature-line"></div>
            <p><strong>Operations Manager</strong></p>
            <p style="font-size: 8pt; margin: 0;">Date: ___________</p>
        </div>
    </div>

    <div style="clear: both; margin-top: 30px; text-align: center; font-size: 8pt; font-style: italic;">
        --- END OF DOCUMENT ---
    </div>
</body>
</html>
